# Declariatively define labels for a Github repository.
# See https://github.com/b4b4r07/github-labeler
labels:
  - name: label1
    description: First label
    color: 9CCC65
  - name: label2
    description: Second label
    color: FFA000
  - name: label3
    description: Third label
    color: AAFF00
  - name: label4
    description: Fourth label
    color: 00FFAA
  - name: docs
    description: Documentation updates
    color: DDDDDD

repos:
- name: scowalt/actions-labeler-example
  labels:
  - label1
  - label2
  - label3
  - docs
